import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AlterModalProvider from './_provider/AlterModalProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'XClone.com',
  description: 'Generated by create next app',
  icons: {
    icon: '/X.ico',
  },
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AlterModalProvider>{children}</AlterModalProvider>
      </body>
    </html>
  );
}
