import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import PathRecordProvider from '@/app/_provider/PathRecordProvider';
import AlterModal from '@/app/_component/_alter/AlterModal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'XClone.com',
  description: 'Generated by create next app',
  icons: {
    icon: '/X.ico',
  },
  openGraph: {
    title: 'XClone.com',
    description:
      'This is a clone project based on the X site. It was created with the goal of practicing front-end and back-end technologies and implementing real service-level functions.',
    url: `https://localhost:9090`,
    siteName: 'XClone.com',
    images: [
      {
        url: `${process.env.SERVER_URL}/api/image/X.jpg`,
        width: 400,
        height: 400,
      },
    ],
    locale: 'ko_KR',
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'XClone.com',
    description:
      'This is a clone project based on the X site. It was created with the goal of practicing front-end and back-end technologies and implementing real service-level functions.',
    images: [`${process.env.SERVER_URL}/api/image/X.jpg`],
  },
};

type Props = {
  children: React.ReactNode;
  flow: React.ReactNode;
};

export default function RootLayout({ children, flow }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PathRecordProvider>
          {children}
          {flow}
          <AlterModal />
        </PathRecordProvider>
      </body>
    </html>
  );
}
